# Generated by Django 4.0.4 on 2022-06-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('fecha_eliminacion', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('modelobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entidades.modelobase')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre de la Persona')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos de la persona')),
                ('documento', models.IntegerField(verbose_name='Cedula de la persona')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Numero de celular de la persona')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion de la persona')),
            ],
            bases=('entidades.modelobase',),
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('modelobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entidades.modelobase')),
                ('nombre_entidad', models.CharField(max_length=300, verbose_name='Nombre de la entidad')),
                ('nit', models.CharField(max_length=20, verbose_name='Numero de identificacion tributaria')),
                ('formato', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion Entidad')),
                ('rector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.persona')),
            ],
            bases=('entidades.modelobase',),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('modelobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entidades.modelobase')),
                ('nombre_contratista', models.CharField(max_length=120, verbose_name='Nombre de contratista')),
                ('documento_contratista', models.IntegerField(verbose_name='Numero documento contratista')),
                ('objeto', models.CharField(max_length=100, verbose_name='Objeto del contrato')),
                ('valor_contrato', models.IntegerField(verbose_name='Valor contrato')),
                ('plazo_ejecucion', models.CharField(max_length=30, verbose_name='Plazo ejecutar contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio de contrato')),
                ('fecha_terminacion', models.DateField(verbose_name='Fecha finalizacion contrato')),
                ('vigilancia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vigilancia contrato')),
                ('entidad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.entidad')),
            ],
            bases=('entidades.modelobase',),
        ),
    ]
