# Generated by Django 4.0.4 on 2022-07-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_remove_contrato_documento_contratista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('modelobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entidades.modelobase')),
                ('numero_item', models.IntegerField(max_length=500, unique=True)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion del item')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad del item')),
                ('unidad_medida', models.CharField(max_length=100, verbose_name='Unidad de medida del item')),
                ('contrato_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.contrato')),
            ],
            bases=('entidades.modelobase',),
        ),
    ]
