# Generated by Django 4.0.4 on 2022-07-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='numero_item',
            field=models.IntegerField(unique=True),
        ),
    ]
